### ISSUE TITLE
Extract report commits to external repository

### ISSUE THREAD

**Issue by fivitti** [gut-space/aquarius#7]
Report files takes up a lot of space (PDF, DOC, JPEG files with many modifications).
It isn't necessary to download it with source code, but increase size of repository.

We want:

- [x] Move reports, images and documentations (exclude strictly developers docs as installation and configuration) to external repository
- [x] Rewrite history to remove these files
- [x] Rewrite history to remove other reports big files
- [x] Keep history of work under reports in external repository (especially history of @eweomern )

Some references:

- [Removing files from history](https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository)
- [Github guide for removing files from history](https://help.github.com/en/github/managing-large-files/removing-files-from-a-repositorys-history)
- [BFG Repo-cleaner](https://rtyley.github.io/bfg-repo-cleaner/)
- [Remove large .pack file](https://stackoverflow.com/questions/11050265/remove-large-pack-file-created-by-git)

**Comment by tomaszmrugalski** [comment]
We now have [historic repo](https://github.com/gut-space/satnogs) with all history (and 185MB+ stuff) preserved. There's also the [new clean repo](https://github.com/gut-space/aquarius), which we'll use from now on.

Personally, I consider this clean-up complete. If you agree, please close. If not, let's continue cleaning up.

**Comment by fivitti** [comment]
I check the repo using the tools from this [thread](https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history).
It shown that all big files are removed.

I also used a diff tool to compare the directories with old and new repositories and it looks that all important files are still included.

Good job!
